service: HackerNewsJobScraper

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    PUSHBULLET_API_KEY: ${env:PUSHBULLET_API_KEY}
    SUBSCRIBE_EMAIL_PASS: ${env:SUBSCRIBE_EMAIL_PASS}
    SUBSCRIBE_EMAIL_USER: ${env:SUBSCRIBE_EMAIL_USER}
    SUBSCRIBE_EMAIL_HOST: ${env:SUBSCRIBE_EMAIL_HOST}

functions:
  cron:
    handler: handler.cron
    events:
      - schedule: cron(0 14 ? * MON-FRI *)
